// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: demo1.proto

package HelloTest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to Type:
	//	*Req_Addr
	//	*Req_Phone
	Type isReq_Type `protobuf_oneof:"type"`
	Age  int32      `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *Req) Reset() {
	*x = Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req) ProtoMessage() {}

func (x *Req) ProtoReflect() protoreflect.Message {
	mi := &file_demo1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req.ProtoReflect.Descriptor instead.
func (*Req) Descriptor() ([]byte, []int) {
	return file_demo1_proto_rawDescGZIP(), []int{0}
}

func (x *Req) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *Req) GetType() isReq_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Req) GetAddr() string {
	if x, ok := x.GetType().(*Req_Addr); ok {
		return x.Addr
	}
	return ""
}

func (x *Req) GetPhone() string {
	if x, ok := x.GetType().(*Req_Phone); ok {
		return x.Phone
	}
	return ""
}

func (x *Req) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type isReq_Type interface {
	isReq_Type()
}

type Req_Addr struct {
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3,oneof"`
}

type Req_Phone struct {
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3,oneof"`
}

func (*Req_Addr) isReq_Type() {}

func (*Req_Phone) isReq_Type() {}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_demo1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_demo1_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_demo1_proto protoreflect.FileDescriptor

var file_demo1_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x64, 0x65, 0x6d, 0x6f, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x64,
	0x65, 0x6d, 0x6f, 0x31, 0x22, 0x61, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x16, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x42,
	0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x1c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x37, 0x0a, 0x0b, 0x54, 0x65, 0x73, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x31, 0x12, 0x28, 0x0a, 0x09, 0x54, 0x65, 0x73, 0x74, 0x44, 0x65, 0x6d, 0x6f,
	0x31, 0x12, 0x0a, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e,
	0x64, 0x65, 0x6d, 0x6f, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x17,
	0x5a, 0x15, 0x2e, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x3b, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x54, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_demo1_proto_rawDescOnce sync.Once
	file_demo1_proto_rawDescData = file_demo1_proto_rawDesc
)

func file_demo1_proto_rawDescGZIP() []byte {
	file_demo1_proto_rawDescOnce.Do(func() {
		file_demo1_proto_rawDescData = protoimpl.X.CompressGZIP(file_demo1_proto_rawDescData)
	})
	return file_demo1_proto_rawDescData
}

var file_demo1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_demo1_proto_goTypes = []interface{}{
	(*Req)(nil),      // 0: demo1.Req
	(*Response)(nil), // 1: demo1.Response
}
var file_demo1_proto_depIdxs = []int32{
	0, // 0: demo1.TestServer1.TestDemo1:input_type -> demo1.Req
	1, // 1: demo1.TestServer1.TestDemo1:output_type -> demo1.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_demo1_proto_init() }
func file_demo1_proto_init() {
	if File_demo1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_demo1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_demo1_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Req_Addr)(nil),
		(*Req_Phone)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_demo1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demo1_proto_goTypes,
		DependencyIndexes: file_demo1_proto_depIdxs,
		MessageInfos:      file_demo1_proto_msgTypes,
	}.Build()
	File_demo1_proto = out.File
	file_demo1_proto_rawDesc = nil
	file_demo1_proto_goTypes = nil
	file_demo1_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TestServer1Client is the client API for TestServer1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestServer1Client interface {
	TestDemo1(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Response, error)
}

type testServer1Client struct {
	cc grpc.ClientConnInterface
}

func NewTestServer1Client(cc grpc.ClientConnInterface) TestServer1Client {
	return &testServer1Client{cc}
}

func (c *testServer1Client) TestDemo1(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/demo1.TestServer1/TestDemo1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServer1Server is the server API for TestServer1 service.
type TestServer1Server interface {
	TestDemo1(context.Context, *Req) (*Response, error)
}

// UnimplementedTestServer1Server can be embedded to have forward compatible implementations.
type UnimplementedTestServer1Server struct {
}

func (*UnimplementedTestServer1Server) TestDemo1(context.Context, *Req) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestDemo1 not implemented")
}

func RegisterTestServer1Server(s *grpc.Server, srv TestServer1Server) {
	s.RegisterService(&_TestServer1_serviceDesc, srv)
}

func _TestServer1_TestDemo1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer1Server).TestDemo1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/demo1.TestServer1/TestDemo1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer1Server).TestDemo1(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

var _TestServer1_serviceDesc = grpc.ServiceDesc{
	ServiceName: "demo1.TestServer1",
	HandlerType: (*TestServer1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestDemo1",
			Handler:    _TestServer1_TestDemo1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo1.proto",
}
